# Generated by Django 4.2 on 2024-07-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
